plugins:
- jekyll-redirect-from
- jekyll-sitemap
- algoliasearch-jekyll

# ---
# Define URLs
# ---
url: http://localhost:4000
BASE_URL: http://localhost:4000
staticurl: http://localhost:4000/all_static
imgurl: https://images.plot.ly/plotly-documentation/
plotlyjs_download_url: https://cdn.plot.ly/plotly-latest.min.js


# ---
# Excludes
# ---
exclude:
  - _posts/plotly_js/
  - _posts/r/
#  - _posts/python/
#  - _posts/python-next/
  - _posts/reference_pages/
  - _posts/ggplot2/
  - _posts/julia/
  - _posts/scala/
  - _posts/matlab/
  - _posts/matplotlib/
  - _posts/nodejs/
  - _posts/pandas/
  - _posts/numpy/
  - _posts/dashboards/
  - _posts/ipython-notebooks/
  - _posts/scikit-learn/
  - vendor
  - "*.Rmd"
  - .idea/

# ---
# Markdown / Syntax
# ---
kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

# ---
# Algolia Search
# ---
# Run make search_readme for more information on search
algolia:
  application_id: '7EK9KHJW8M'
  index_name:     'python_docs'
  read_only_api_key: '4dae07ded6a721de73bde7356eec9280'
  excluded_files:
    # - '*.ipynb'
    - '*.png'
    - '*.Rmd'
    - '*.R'
    - '_posts/dashboards'
    - '_posts/ggplot2'
    - '_posts/ipython-notebooks'
    - '_posts/julia'
    - '_posts/matlab'
    - '_posts/matplotlib'
    - '_posts/misc'
    - '_posts/nodejs'
    - '_posts/numpy'
    - '_posts/pandas'
    - '_posts/plotly_js'
    - '_posts/r'
    - '_posts/reference_pages'
    - '_posts/scala'
    - '_posts/scikit'
    - '_posts/temp'
  settings:
    attributesToIndex:
      - name
      - description
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
